
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Lmsensorsbeat. They are
grouped in the following categories:

* <<exported-fields-common>>
* <<exported-fields-temp>>

[[exported-fields-common]]
=== Common Fields

Contains common fields available in all lmsensors pulls.



==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp of when the measurements were taken. The precision is in milliseconds. The timezone is UTC.


==== type

type: string

required: True

Set to "lmsensors" to indicate that the statistics come from this service.


==== beat.name

type: string

Name of the Beat sending the events. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

type: string

The hostname as returned by the operating system on which the Beat is running.


[[exported-fields-temp]]
=== Temperature Fields

Contains sensor data from temperature sensors



==== sensors.temp1

type: float

The value of the temp1 sensor (typically in degrees Celsius)


==== sensors.temp2

type: float

The value of the temp2 sensor (typically in degrees Celsius)


==== sensors.temp3

type: float

The value of the temp3 sensor (typically in degrees Celsius)


==== sensors.temp4

type: float

The value of the temp4 sensor (typically in degrees Celsius)


==== sensors.temp5

type: float

The value of the temp5 sensor (typically in degrees Celsius)


